Feature Bubble Sort
Milypm/Ruby-Bubble-Sort pull request #1
Opened 2020-11-20 23:56 UTC by carloso0114

In this project we manage to create two methods that sort an array of numbers and strings.
The tools that we use were:
-Ruby
-Rubocop

It consists of two different methods, the second one includes a yield and a block statement with an argument as required. 
Only works with an array of strings
The first method works only with an array of integers.

2020-11-21 02:05 UTC, kitpao requested changes
# 👋 Hello @Milypm and @carloso0114 

🌟 Great job with your logic, it works perfectly 💯 Your readme and pull request messages are very useful as well (you just have 1 detail in the Readme). 

📝 Please check the inline commits to see and fix the remaining issues ⏬ 

- Your commits are descriptive, but for next time try to be consistent and write your commits in the imperative tense, as stated in [the article pointed in pathwright](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/)

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me on slack as @kitpao
##### 🌟  If you have feedback about my reviews I would appreciate it if you could leave a recommendation in LinkedIn 💌 or let me know in Slack if you see improvements to be done 😄  

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-11-21 02:05 UTC, kitpao commented on README.md
> +* Open the ruby file with the terminal running the command line "ruby bubble-sort.rb"
- [x] I copy pasted your instruction and it gave me an error, please fix it. Remember that `-` is not the same as `_`

2020-11-21 02:05 UTC, kitpao commented on bubble_sort.rb
> +puts bubble_sort([4, 3, 5, 1, 2])
- [ ] About good practices, please do not commit debugging code (generally include `puts`, `print` or `p`). Later in the course, you will learn how to add automated tests where you will be able to put your examples ;) Please delete this line
![image](https://user-images.githubusercontent.com/53256139/99864765-cfeee600-2b6a-11eb-8ec7-a84406a5e894.png)

2020-11-21 02:05 UTC, kitpao commented on bubble_sort.rb
> +puts a
- [ ] About good practices, please do not commit debugging code (generally include `puts`, `print` or `p`). Later in the course, you will learn how to add automated tests where you will be able to put your examples ;) Please delete these lines
![image](https://user-images.githubusercontent.com/53256139/99864765-cfeee600-2b6a-11eb-8ec7-a84406a5e894.png)

2020-11-23 16:29 UTC, Georjane approved these changes
Status: PR Approved ✔️✔️
Hi Team🙌
Congratulations on your Bubble Sort Project. 🎊🎉
Your project looks great and you implemented all changes required by the previous TSE. You can go ahead and merge this PR. 👍👍

Goodluck and Happy Coding 💻

2020-11-23 16:32 UTC, merged